### ISSUE TITLE
Can´t compile Fortran code properly

### ISSUE THREAD

**Issue by gerardoeg** [aewallin/ppp-tools#3]
Hi! Thanks for your contribution.

I was trying to compile Fortran code for NRCan.

If I try with  **gfortran -o gpsppp *.f** it fails: ld returned 1 exit status. some packages or variables not found.

If I try with **gfortran -o gpsppp *.f** it compiles the code, generates the executable. but when I run the example it says exec format error in the python script.

Any clue of what is going on?

Thank you in advance

**Comment by aewallin** [comment]
my version of gpsppp (might be old by now) and gfortran (on ubuntu 18.04lts):
`Dist34613b/source$ gfortran --version
GNU Fortran (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
`
compile:
`Dist34613b/source$ gfortran -o gpsppp2 *.f`
(no output at all)

run:
`
Dist34613b/source$ ./gpsppp2
-------------------------------------------------------------------------------
GPS Precise Point Positioning (CSRS-PPP ver.        1.05/34613/2013-12-12)      
-------------------------------------------------------------------------------
+Enter MEASUREMENT input file name    :1st_place_medal: 
`

if there are errors from the ppp-tools python scripts then please include the error message here.

**Comment by gerardoeg** [comment]
**for the gfortran --version I get:**
gfortran -o gpsppp *.f
/tmp/ccanNO5J.o: In function `vmfintrp_':
gpspace.f:(.text+0x2408d): undefined reference to `vmf1_ht_'
gpspace.f:(.text+0x240c5): undefined reference to `vmf1_'
/tmp/ccanNO5J.o: In function `iono2nd_':
gpspace.f:(.text+0x26e6a): undefined reference to `igrf12syn_'
/tmp/ccanNO5J.o: In function `bodyt_':
gpspace.f:(.text+0x2f468): undefined reference to `dehanttideinel_'
/tmp/ccanNO5J.o: In function `rderp_':
gpspace.f:(.text+0x30926): undefined reference to `iers_cmp_2015_'
gpspace.f:(.text+0x30990): undefined reference to `iers_cmp_2015_'
gpspace.f:(.text+0x30a39): undefined reference to `iers_cmp_2015_'
/tmp/ccanNO5J.o: In function `rdmet_':
gpspace.f:(.text+0x30e8b): undefined reference to `gpt_'
gpspace.f:(.text+0x318c0): undefined reference to `gpt2_'
/tmp/ccanNO5J.o: In function `MAIN__':
gpspace.f:(.text+0x97507): undefined reference to `oloadn_'
gpspace.f:(.text+0x979c6): undefined reference to `gpt_'
gpspace.f:(.text+0x9d066): undefined reference to `gmf_'
collect2: error: ld returned 1 exit status

**Comment by aewallin** [comment]
I suspect that you are missing some files, which should contain the functions that **gpspace.f** wants. Did you get a working/complete source package from nrcan?

I don't seem to have a **gpspace.f** file att all in my version

I do have the following files, which probably have some of the functions you are missing **gmf.f** and **gpt2.f** and **rdmet.f** - do you have these?

**Comment by gerardoeg** [comment]
Yeap, you are right. The source files are now located in external-source folder in github. And gspace.f call all the function, I copied all the files in the main folder and I was succeful at compiling it. The exit is different, but now it is running at least. I will try with the python script now.

Now output is:

 ./gpsppp

```
 ******************************************************
 *              IGRF SYNTHESIS PROGRAM                *
 *                                                    *
 * A program for the computation of geomagnetic       *
 * field elements from the International Geomagnetic  *
 * Reference Field (12th generation) as revised in    *
 * December 2014 by the IAGA Working Group V-MOD.     *
 *                                                    *
 * It is valid for dates from 1900.0 to 2020.0,       *
 * values up to 2025.0 will be computed but with      *
 * reduced accuracy. Values for dates before 1945.0   *
 * and after 2010.0 are non-definitive, otherwise the *
 * values are definitive.                             *
 *                                                    *
 * Susan Macmillan          British Geological Survey *
 *                           IAGA Working Group V-MOD *
 ******************************************************

 Enter name of output file (30 characters maximum)
 or press "Return" for output to screen

 Enter value for coordinate system:
 1 - geodetic (shape of Earth is approximated by a spheroid)
 2 - geocentric (shape of Earth is approximated by a sphere)

```

thank you for your prompt reply. I will go on with my project.

**Comment by gerardoeg** [comment]
Just to let you close the issue, I realized I have not the proper fortran code. 

So now my question is, where can I get it? Thank

**Comment by aewallin** [comment]
A license for gpsppp for non-commercial use is usually available from NRC Canada. You need to write them and describe your use-case and ask for a license.
https://www.nrcan.gc.ca/maps-tools-publications/tools/geodetic-reference-systems-tools/tools-applications/10925#ppp

**Comment by aewallin** [comment]
closing this for now - please reopen or create a new issue if needed.
